name: SUPERPORTAL
version: '${project.version}'
main: com.promc.SUPERPORTAL
api-version: 1.16
depend:
  - WorldGuard
softdepend:
  - PlaceholderAPI
authors: [ TUCAOEVER ]

commands:
  superportal:
    aliases:
      - "sportal"
      - "sp"